export const voices = [
    {
        id: 'voice1',
        imgUrl: 'voice1.png',
        category: 'Teacher',
        bgColor: '#E3D2E1',
        borderColor: '#E3D2E1',
        hover: '#620058',
    },
    {
        id: 'voice2',
        imgUrl: 'voice2.png',
        category: 'Marketing',
        bgColor: '#E989DF',
        borderColor: '#E989DF',
        hover: '#620058',
    },
    {
        id: 'voice3',
        imgUrl: 'voice3.png',
        category: 'Author',
        bgColor: '#FF5BEF',
        borderColor: '#FF5BEF',
        hover: '#620058',
    },
    {
        id: 'voice4',
        imgUrl: 'voice4.png',
        category: 'Youtuber',
        bgColor: '#E989DF',
        borderColor: '#E989DF',
        hover: '#620058',
    },
    {
        id: 'voice5',
        imgUrl: 'voice5.png',
        category: 'Animator',
        bgColor: '#E3D2E1',
        borderColor: '#E3D2E1',
        hover: '#620058',
    },
    {
        id: 'voice6',
        imgUrl: 'voice6.png',
        category: 'Podcast',
        bgColor: '#E989DF',
        borderColor: '#E989DF',
        hover: '#620058',
    },
]